name: google_map_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  
  # ★ここに追加（SDK設定付き）
  flutter_localizations:
    sdk: flutter

  flutter_rating_bar: ^4.0.1
  geolocator: ^14.0.2
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.13.1
  cloud_firestore: ^6.1.0
  firebase_core: ^4.2.1
  firebase_storage: ^13.0.4
  image_picker: ^1.2.1
  cloud_functions: ^6.0.4
  analytics: ^2.0.3
  firebase_auth: ^6.1.2
  firebase_app_check: ^0.4.1+2
  table_calendar: ^3.2.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  firebase_messaging: ^16.1.1
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# ここからFlutterの設定
flutter:
  uses-material-design: true

  assets:
    - image/logo.jpg